language: java

jdk:
  - oraclejdk8
  - openjdk8

os:
  - linux

before_install:
  - mysql -uroot < Database/CREATE-DATABASE.SQL
  - mysql -uroot < Database/INSERTS.SQL

script:
  - mvn spring-boot:run
  - mvn clean install spring-boot:repackage

services:
  - mysql
