language: java

jdk:
  - oraclejdk8
  - openjdk8

os:
  - linux

before_install:
  - mysql -e < Database/CREATE-DATABASE.SQL
  - mysql -e < Database/INSERTS.SQL

script:
  - mvn spring-boot:run

services:
  - mysql
