language: java

jdk:
  - oraclejdk8
  - openjdk8

os:
  - linux

before_install:
  - pushd Database
  - python3 generate_inserts.py
  - mysql -uroot < CREATE-DATABASE.SQL
  - mysql -uroot < INSERTS.SQL
  - popd >/dev/null

script:
  - mvn spring-boot:run
  - mvn clean install spring-boot:repackage

services:
  - mysql
